import { Inter } from "next/font/google";
import "./globals.css";  
import CookieConsentComponent from "./cookieConsentComponent/CookieConsent";
// import LenisScroll from "./LenisScroll";
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.min.js';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      
      <body className={inter.className}>
      {/* <h1>Root Layout</h1> */}
        {children}
        
          <CookieConsentComponent/>
          {/* <LenisScroll/> */}
        </body>
    </html>
  );
}
